[package]
name = "tic-tac-boom"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
flash = "0.0.6"
libloading = "0.8.8"
quick-js = "0.4.1"
rand = "0.9.2"
rutie = "0.9"

[features]
ocaml = []
